In [129]:
import pandas as pd
df=pd.read_csv("D:/customer_shopping_behavior.csv")

In [130]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [132]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [133]:
df.shape

(3900, 18)

In [134]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [135]:
df["Review Rating"]= df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))
df["Review Rating"]

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [136]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_") # all the column names are in snake casing  we have converted it becuase  to avoide error we  when we'll do analysis in sql
df=df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"})

In [137]:
# Create a Colunms age_group
labels=["Young Adult","Adult","Middle-aged","Senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)
df[["age","age_group"]]

      age    age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [138]:
# create column purchase_frequency_days 
freq_to_days = { "Daily": 1,"Weekly": 7,"Bi-Weekly": 14,"Fortnightly": 14,"Monthly": 30,"Quarterly": 90,"Annually": 365}
df["purchase_frequency_days"]=df["frequency_of_purchases"].map(freq_to_days)
df["purchase_frequency_days"]

0        14.0
1        14.0
2         7.0
3         7.0
4       365.0
        ...
3895      7.0
3896     14.0
3897     90.0
3898      7.0
3899     90.0
Name: purchase_frequency_days, Length: 3900, dtype: float64

In [139]:
df[["frequency_of_purchases","purchase_frequency_days"]]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                     14.0
1               Fortnightly                     14.0
2                    Weekly                      7.0
3                    Weekly                      7.0
4                  Annually                    365.0
...                     ...                      ...
3895                 Weekly                      7.0
3896              Bi-Weekly                     14.0
3897              Quarterly                     90.0
3898                 Weekly                      7.0
3899              Quarterly                     90.0

[3900 rows x 2 columns]

In [140]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [141]:
df[['discount_applied', 'promo_code_used']] 
# do we need both colunms

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [142]:
(df['discount_applied']==df['promo_code_used']).all()

True

In [143]:
df=df.drop('promo_code_used',axis=1)

In [144]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
# Connecting to My SQL

In [174]:
# Import libraries
import pandas as pd
from sqlalchemy import create_engine

In [176]:
# Create connection
engine = create_engine("mysql+pymysql://root:Richa%402002@localhost/customer_shopping_behavior")

In [178]:
# Check your dataframe BEFORE upload 
print(df.head())
print(df.info())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                     14.0
1            Fortnightly  Young Adult                     14.0
2                 Weekly  Middle-aged                      7.0
3                 Weekly  Young Adult                      7.0
4               Annually  Middle-aged                    365.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3316 non-null   float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 552.6+ KB
None

In [180]:
# Upload dataframe to MySQL

df.to_sql(
    name="customers",        
    con=engine,
    if_exists="replace",     
    index=False
)

3900